#!/usr/bin/env python

from pointdexter.runner import run_command
from collections import defaultdict
import json

templ = "{file}    {id}    {line}    {severity}    {message}"

stdout, stderr, exit = run_command([
    "cppcheck",
    ".",
    "-q",
    "-j",
    "8",
    "--enable=all",
    "--template",
    templ
])

ret = defaultdict(list)

for line in stderr.splitlines():
    fil, eyedee, line, severity, message = line.split("    ")
    ret[severity].append({
        "file": fil,
        "tag": eyedee,
        "line": line,
        "description": message
    })

severity = 'ok'
if ret['warning'] != []:
    severity = 'warning'

if ret['error'] != []:
    severity = 'error'

print json.dumps({
    "severity": "error",
    "data": ret,
    "type": "cppcheck"
})
