#!/usr/bin/env python

from pointdexter.runner import run_command
from collections import defaultdict
import json
import re

stdout, stderr, exit = run_command([
    "flake8",
    ".",
    "-r"
])

FLAKE_RE = re.compile(
    r'(?P<file>.*):(?P<line>.*):((?P<col>.*):)? (?P<tag>(W|E)\d*) (?P<description>.*)'
)

ret = defaultdict(list)

for line in stdout.splitlines():
    obj = FLAKE_RE.match(line).groupdict()
    typ = {'E': "error", "W": "warning"}[obj['tag'][0]]
    ret[typ].append(obj)

print json.dumps({
    "data": ret,
    "type": "flake8"
})
