#!/usr/bin/env python

from collections import defaultdict
import json
import os

flags = {
    "warning": "warning",
    "error": "error",
}

but_not = {
    "error": [
        "-Werror"
    ]
}

ret = defaultdict(list)


files = os.listdir(".")
for fp in files:
    if fp.endswith(".build"):
        if os.path.islink(fp):
            continue
        for line in open(fp, 'r').readlines():
            for flag in flags:
                if flag in line:
                    dont_append = False
                    for nflag in but_not[flag]:
                        if nflag in line:
                            dont_append = True

                    if not dont_append:
                        ret[flags[flag]].append(line)


severity = 'ok'
if ret['warning'] != []:
    severity = 'warning'

if ret['error'] != []:
    severity = 'error'


print json.dumps({
    "data": ret,
    "severity": severity,
    "type": "build-log"
})
