#!/usr/bin/env python

from pointdexter.runner import run_command
from collections import defaultdict
import json

stdout, stderr, exit = run_command([
    "sh",
    "-c",
    "find -iname \*.desktop -print0 |"
    "xargs --no-run-if-empty --null -n1 desktop-file-validate"
])

ret = defaultdict(list)

for line in stdout.splitlines():
    fil, severity, text = line.rsplit(": ", 2)
    ret[severity].append({
        "file": fil,
        "tag": "desktop-%s" % (severity),
        "description": text
    })


print json.dumps({
    "data": ret,
    "type": "suspicious-source"
})
